steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/python_dice_website:$SHORT_SHA'
  - '-f'
  - 'DockerFile.Docker'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/python_dice_website:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'pythondicewebsite'
    - '--image'
    - 'gcr.io/$PROJECT_ID/python_dice_website:$SHORT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'