FROM python:3.7-slim

RUN mkdir /usr/pydiceweb
WORKDIR /usr/pydiceweb

COPY requirements.txt ./
COPY .coveragerc ./
COPY pylintrc ./

RUN pip install --no-cache-dir -r requirements.txt

COPY python_dice_website ./python_dice_website

RUN python -m pytest --black --isort --pylint --cov python_dice_website

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 python_dice_website.src.app:APP